export const AlertActionTypes = {
    SHOW_ALERT_SUCCESS: 'SHOW_ALERT_SUCCESS',
    SHOW_ALERT_WARNING: 'SHOW_ALERT_WARNING',
    SHOW_ALERT_ERROR: 'SHOW_ALERT_ERROR',
    DISMISS_ALERT: 'DISMISS_ALERT'
}

export const CLEAR_ERROR = 'CLEAR_ERROR'
