export const BooksActionTypes = {
    BOOKS_LIST_SUCCESS: 'BOOKS_LIST_SUCCESS',
    BOOKS_LIST_FAILURE: 'BOOKS_LIST_FAILURE',
    BOOKS_DETAILS_SUCCESS: 'BOOKS_DETAILS_SUCCESS',
    BOOKS_DETAILS_FAILURE: 'BOOKS_DETAILS_FAILURE',
    BOOKS_CATEGORIES_SUCCESS: 'BOOKS_CATEGORIES_SUCCESS',
    BOOKS_CATEGORIES_FAILURE: 'BOOKS_CATEGORIES_FAILURE',
    BOOKS_GENRES_SUCCESS: 'BOOKS_GENRES_SUCCESS',
    BOOKS_GENRES_FAILURE: 'BOOKS_GENRES_FAILURE'
}
