export const OrderActionTypes = {
    ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',
    ORDER_LIST_FAILURE: 'ORDER_LIST_FAILURE',
    ORDER_DETAIL_SUCCESS: 'ORDER_DETAIL_SUCCESS',
    ORDER_DETAIL_FAILURE: 'ORDER_DETAIL_FAILURE'
}

export const WishlistActionTypes = {
    WHISHLIST_GET_SUCCES: 'WHISHLIST_GET_SUCCES',
    WHISHLIST_GET_FAILURE: 'WHISHLIST_GET_FAILURE',
    WISHLIST_UPDATE_SUCCESS: 'WISHLIST_UPDATE_SUCCESS',
    WISHLIST_UPDATE_FAILURE: 'WISHLIST_UPDATE_FAILURE'
}

export const CartActionTypes = {
    CART_GET_SUCCESS: 'CART_GET_SUCCESS',
    CART_GET_FAILURE: 'CART_GET_FAILURE',
    CART_UPDATE_SUCCESS: 'CART_UPDATE_SUCCESS',
    CART_UPDATE_FAILURE: 'CART_UPDATE_FAILURE'
}
