export const UserActionTypes = {
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGOUT: 'USER_LOGOUT',
}

export const CustomerActionTypes = {
    CUSTOMER_RECORD_GET_SUCCESS: 'CUSTOMER_RECORD_GET_SUCCESS',
    CUSTOMER_RECORD_GET_FAILURE: 'CUSTOMER_RECORD_GET_FAILURE',
    CUSTOMER_RECORD_UPDATE_SUCCESS: 'CUSTOMER_RECORD_UPDATE_SUCCESS',
    CUSTOMER_RECORD_UPDATE_FAILURE: 'CUSTOMER_RECORD_UPDATE_FAILURE'
}

export const ShippingAddressActionTypes = {
    SHIPPING_ADDRESS_GET_SUCCESS: 'SHIPPING_ADDRESS_GET_SUCCESS',
    SHIPPING_ADDRESS_GET_FAILURE: 'SHIPPING_ADDRESS_GET_FAILURE',
    SHIPPING_ADDRESS_UPDATE_SUCCESS: 'SHIPPING_ADDRESS_UPDATE_SUCCESS',
    SHIPPING_ADDRESS_UPDATE_FAILURE: 'SHIPPING_ADDRESS_UPDATE_FAILURE'
}
